import { CompanyInfo, CustomerInfo, DocumentModel, ProductCatalogItem } from '../types';
import { calculateDocumentTotals } from './documentCalculations';

export const initialCompanies: CompanyInfo[] = [
  {
    id: 'company-hq',
    profileName: 'สำนักงานใหญ่ (กรุงเทพฯ)',
    isDefault: true,
    name: 'บริษัท สยาม คลาวด์ เทคโนโลยี จำกัด',
    nameEn: 'Siam Cloud Technology Co., Ltd.',
    taxId: '0105561089123',
    branchType: 'headquarters',
    branchNo: '00000',
    address: '88/1 อาคารสยามทาวเวอร์ ชั้น 18 ถนนสุขุมวิท แขวงคลองเตยเหนือ เขตวัฒนา กรุงเทพฯ 10110',
    addressEn: '88/1 Siam Tower, 18th Fl., Sukhumvit Rd., Khlong Toei Nuea, Watthana, Bangkok 10110',
    phone: '02-714-8999, 089-123-4567',
    email: 'contact@siamcloud.co.th',
    website: 'www.siamcloud.co.th',
    signatureName: 'นายสมชาย รุ่งเรืองทรัพย์',
    signaturePosition: 'กรรมการผู้จัดการ (Managing Director)',
    promptPayId: '0105561089123',
    showPaymentSlipNotice: true,
    paymentSlipNotice: 'โอนเงินแล้ว กรุณาส่งสลิปหลักฐานการชำระเงินที่ 02-714-8999 หรือ contact@siamcloud.co.th',
    defaultRemarks: 'กรุณาตรวจสอบความถูกต้องของเอกสาร หากมีข้อแก้ไขกรุณาแจ้งให้ทราบภายใน 7 วันทำการ',
    defaultTerms: '1. การชำระเงินโอนเข้าบัญชีธนาคารตามที่ระบุในเอกสาร\n2. กรณีหักภาษี ณ ที่จ่าย กรุณานำส่งหนังสือรับรองการหักภาษี ณ ที่จ่าย (50 ทวิ)',
    defaultPaymentTerms: '',
    bankAccounts: [
      {
        id: 'bank-1',
        bankName: 'ธนาคารกสิกรไทย (KBANK)',
        accountName: 'บจก. สยาม คลาวด์ เทคโนโลยี',
        accountNumber: '789-2-34567-8',
        branch: 'สาขาสุขุมวิท 21',
        isDefault: true,
      },
      {
        id: 'bank-2',
        bankName: 'ธนาคารไทยพาณิชย์ (SCB)',
        accountName: 'บจก. สยาม คลาวด์ เทคโนโลยี',
        accountNumber: '123-4-56789-0',
        branch: 'สาขาอโศก',
        isDefault: false,
      },
    ],
  },
  {
    id: 'company-branch-1',
    profileName: 'สาขาเชียงใหม่ (00001)',
    isDefault: false,
    name: 'บริษัท สยาม คลาวด์ เทคโนโลยี จำกัด (สาขาเชียงใหม่)',
    nameEn: 'Siam Cloud Technology Co., Ltd. (Chiang Mai Branch)',
    taxId: '0105561089123',
    branchType: 'branch',
    branchNo: '00001',
    address: '99/5 ถนนนิมมานเหมินท์ ตำบลสุเทพ อำเภอเมืองเชียงใหม่ จังหวัดเชียงใหม่ 50200',
    addressEn: '99/5 Nimmanahaeminda Rd., Suthep, Mueang Chiang Mai, Chiang Mai 50200',
    phone: '053-222-888, 089-123-4567',
    email: 'cm-branch@siamcloud.co.th',
    website: 'www.siamcloud.co.th',
    signatureName: 'นางสาวพิมพ์ชนก รัตนโกสินทร์',
    signaturePosition: 'ผู้จัดการสาขา (Branch Manager)',
    promptPayId: '0105561089123',
    showPaymentSlipNotice: true,
    paymentSlipNotice: 'โอนเงินแล้ว กรุณาส่งสลิปหลักฐานการชำระเงินที่ cm-branch@siamcloud.co.th',
    defaultRemarks: 'ติดต่อประสานงานสาขาภาคเหนือ โทร 053-222-888 ในวันและเวลาทำการ',
    defaultTerms: '1. กำหนดชำระเงินตามเงื่อนไขที่ตกลง\n2. กรณีมีข้อสงสัยเกี่ยวกับสินค้าหรือบริการ กรุณาติดต่อสาขาเชียงใหม่โดยตรง',
    defaultPaymentTerms: '',
    bankAccounts: [
      {
        id: 'bank-cm-1',
        bankName: 'ธนาคารกสิกรไทย (KBANK)',
        accountName: 'บจก. สยาม คลาวด์ เทคโนโลยี สาขาเชียงใหม่',
        accountNumber: '456-1-89012-3',
        branch: 'สาขานิมมานเหมินท์ เชียงใหม่',
        isDefault: true,
      },
    ],
  },
];

export const initialCompanyInfo: CompanyInfo = initialCompanies[0];

export const initialCustomers: CustomerInfo[] = [
  {
    id: 'cust-1',
    name: 'บริษัท ดิจิทัล โนวา โซลูชั่นส์ จำกัด',
    nameEn: 'Digital Nova Solutions Co., Ltd.',
    contactPerson: 'คุณกิตติศักดิ์ พัฒนากูล (ผู้จัดการฝ่ายจัดซื้อ)',
    taxId: '0105559078456',
    branchType: 'headquarters',
    branchNo: '00000',
    address: '123/45 อาคารสารทาวเวอร์ ชั้น 12 ถนนพญาไท แขวงทุ่งพญาไท เขตราชเทวี กรุงเทพมหานคร 10400',
    addressEn: '123/45 Saran Tower, 12th Fl., Phaya Thai Rd., Ratchathewi, Bangkok 10400',
    phone: '02-215-9988, 081-555-1234',
    email: 'billing@digitalnova.co.th',
  },
  {
    id: 'cust-2',
    name: 'บริษัท ทรอปิคอล รีเทล กรุ๊ป จำกัด (มหาชน)',
    nameEn: 'Tropical Retail Group PCL',
    contactPerson: 'คุณพิมพ์ใจ รัตนเวช',
    taxId: '0107558000456',
    branchType: 'branch',
    branchNo: '00002',
    address: '999/9 ถนนพระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10310',
    addressEn: '999/9 Rama 9 Rd., Huai Khwang, Bangkok 10310',
    phone: '02-645-8000',
    email: 'finance@tropicalretail.com',
  },
  {
    id: 'cust-3',
    name: 'ห้างหุ้นส่วนจำกัด บางกอก ครีเอทีฟ สตูดิโอ',
    nameEn: 'Bangkok Creative Studio Ltd., Part.',
    contactPerson: 'คุณณัฐพล วงศ์สวัสดิ์',
    taxId: '0103554012389',
    branchType: 'headquarters',
    branchNo: '00000',
    address: '54 ซอยทองหล่อ 13 แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110',
    phone: '086-777-8899',
    email: 'contact@bkkcreative.com',
  },
];

export const initialProductCatalog: ProductCatalogItem[] = [
  {
    id: 'prod-1',
    code: 'SRV-WEB-01',
    name: 'บริการพัฒนาเว็บไซต์และระบบสั่งซื้อออนไลน์ (Custom Web App)',
    description: 'พัฒนาเว็บแอปพลิเคชัน รองรับ Responsive UI และเชื่อมต่อระบบชำระเงิน',
    unit: 'โครงการ',
    unitPrice: 45000,
    isTaxable: true,
  },
  {
    id: 'prod-2',
    code: 'SRV-CLOUD-02',
    name: 'บริการ Cloud Hosting & Server Maintenance รายปี',
    description: 'ดูแลรักษาเซิร์ฟเวอร์ สำรองข้อมูลอัตโนมัติ และบริการด้านความปลอดภัย 99.9% Uptime',
    unit: 'ปี',
    unitPrice: 18000,
    isTaxable: true,
  },
  {
    id: 'prod-3',
    code: 'SRV-SEO-03',
    name: 'บริการ SEO & Digital Marketing Optimization (รายไตรมาส)',
    description: 'ปรับปรุงอันดับการค้นหาบน Google พร้อมรายงานผลวิเคราะห์รายสัปดาห์',
    unit: 'ไตรมาส',
    unitPrice: 24000,
    isTaxable: true,
  },
  {
    id: 'prod-4',
    code: 'LIC-ERP-04',
    name: 'สิทธิ์การใช้งานระบบจัดการคลังสินค้าและใบกำกับภาษี (ERP SaaS)',
    description: 'สิทธิ์ผู้ใช้งาน 5 User พร้อมอบรมการใช้งาน 1 วันทำการ',
    unit: 'ชุด',
    unitPrice: 12500,
    isTaxable: true,
  },
  {
    id: 'prod-5',
    code: 'SRV-DESIGN-05',
    name: 'บริการออกแบบกราฟิกอัตลักษณ์องค์กรและ UI/UX Design',
    description: 'ออกแบบ Corporate Identity, Logo Guide และ Mockup System 10 หน้าจอ',
    unit: 'งาน',
    unitPrice: 20000,
    isTaxable: true,
  },
];

export function createSampleDocuments(): DocumentModel[] {
  const items1 = [
    {
      id: 'item-1',
      code: 'SRV-WEB-01',
      name: 'บริการพัฒนาเว็บไซต์และระบบสั่งซื้อออนไลน์ (Custom Web App)',
      description: 'ระบบสมาชิก, ระบบตะกร้าสินค้า, เชื่อมต่อ Payment Gateway และแดชบอร์ดบริหาร',
      quantity: 1,
      unit: 'โครงการ',
      unitPrice: 45000,
      discountType: 'amount' as const,
      discountValue: 3000,
      isTaxable: true,
      total: 42000,
    },
    {
      id: 'item-2',
      code: 'SRV-CLOUD-02',
      name: 'บริการ Cloud Hosting & Server Maintenance รายปี',
      description: 'High-speed SSD Server, SSL Certificate, Daily Backup พร้อม Support 24/7',
      quantity: 1,
      unit: 'ปี',
      unitPrice: 18000,
      discountType: 'percent' as const,
      discountValue: 0,
      isTaxable: true,
      total: 18000,
    },
  ];

  const totals1 = calculateDocumentTotals(items1, 'excluded', 7, 3);

  const doc1: DocumentModel = {
    id: 'doc-quotation-1',
    type: 'quotation',
    documentNumber: 'QT-202608-001',
    referenceNumber: 'REF-PR-2026-089',
    issueDate: '2026-08-15',
    dueDate: '2026-09-15',
    paymentTerms: 'ยืนราคา 30 วัน (มัดจำ 50% เมื่องานเริ่ม, 50% เมื่องานส่งมอบ)',
    company: initialCompanyInfo,
    customer: initialCustomers[0],
    items: items1,
    notes: 'ราคานี้รวมการอบรมการใช้งานผ่าน Zoom 2 ครั้ง และรับประกันระบบ 1 ปีเต็ม',
    termsAndConditions: '1. กำหนดยืนราคา 30 วันนับจากวันที่เสนอราคา\n2. ระยะเวลาดำเนินงาน 45 วันทำการหลังจากได้รับเงินมัดจำงวดแรก\n3. ขอสงวนสิทธิ์ในการเปลี่ยนแปลงเงื่อนไขหากมีการเพิ่มขอบเขตงาน',
    vatType: 'excluded',
    vatRate: 7,
    withholdingTaxRate: 3,
    ...totals1,
    status: 'approved',
    templateStyle: 'modern',
    language: 'th',
    showPromptPayQR: true,
    promptPayId: initialCompanyInfo.promptPayId,
    selectedBankAccountId: 'bank-1',
    showSignature: true,
    showStamp: false,
    preparedByName: 'นายสมชาย รุ่งเรืองทรัพย์',
    approvedByName: 'นายกิตติศักดิ์ พัฒนากูล',
    createdAt: '2026-08-15T09:00:00.000Z',
    updatedAt: '2026-08-15T09:00:00.000Z',
  };

  // Sample Invoice
  const items2 = [
    {
      id: 'item-inv-1',
      code: 'SRV-WEB-01',
      name: 'ค่างวดที่ 1 (50%): ค่าบริการพัฒนาเว็บไซต์และระบบสั่งซื้อออนไลน์',
      description: 'ตามสัญญาจ้างเลขที่ SCT-2026-008 อ้างอิงใบเสนอราคา QT-202608-001',
      quantity: 1,
      unit: 'งวด',
      unitPrice: 21000,
      discountType: 'amount' as const,
      discountValue: 0,
      isTaxable: true,
      total: 21000,
    },
    {
      id: 'item-inv-2',
      code: 'SRV-CLOUD-02',
      name: 'ค่าบริการ Cloud Hosting & Server Maintenance (ปีแรก)',
      description: 'ระยะเวลาคุ้มครอง 1 ปี (1 ก.ย. 2026 - 31 ส.ค. 2027)',
      quantity: 1,
      unit: 'ปี',
      unitPrice: 18000,
      discountType: 'amount' as const,
      discountValue: 0,
      isTaxable: true,
      total: 18000,
    },
  ];
  const totals2 = calculateDocumentTotals(items2, 'excluded', 7, 3);

  const doc2: DocumentModel = {
    id: 'doc-invoice-1',
    type: 'invoice',
    documentNumber: 'IV-202608-001',
    referenceNumber: 'QT-202608-001',
    issueDate: '2026-08-20',
    dueDate: '2026-09-04',
    paymentTerms: 'เครดิต 15 วัน (โอนเงินเข้าบัญชีธนาคาร)',
    company: initialCompanyInfo,
    customer: initialCustomers[0],
    items: items2,
    notes: 'กรุณาหักภาษี ณ ที่จ่าย 3% (ค่าบริการ) และนำส่งหนังสือรับรองหัก ณ ที่จ่าย (50 ทวิ) ทางอีเมล',
    termsAndConditions: 'กรุณาโอนเงินเข้าบัญชี ธ.กสิกรไทย เลขที่ 789-2-34567-8 พร้อมส่งสลิปหลักฐานมาที่ contact@siamcloud.co.th',
    vatType: 'excluded',
    vatRate: 7,
    withholdingTaxRate: 3,
    ...totals2,
    status: 'pending',
    templateStyle: 'modern',
    language: 'th',
    showPromptPayQR: true,
    promptPayId: initialCompanyInfo.promptPayId,
    selectedBankAccountId: 'bank-1',
    showSignature: true,
    showStamp: true,
    preparedByName: 'นายสมชาย รุ่งเรืองทรัพย์',
    createdAt: '2026-08-20T10:30:00.000Z',
    updatedAt: '2026-08-20T10:30:00.000Z',
  };

  // Sample Receipt / Tax Invoice
  const items3 = [
    {
      id: 'item-rc-1',
      code: 'SRV-SEO-03',
      name: 'บริการ SEO & Digital Marketing Optimization (ไตรมาสที่ 3)',
      description: 'ปรับปรุงโครงสร้างเว็บไซต์ คีย์เวิร์ด และรายงานอันดับประจำเดือน',
      quantity: 1,
      unit: 'ไตรมาส',
      unitPrice: 24000,
      discountType: 'amount' as const,
      discountValue: 0,
      isTaxable: true,
      total: 24000,
    },
  ];
  const totals3 = calculateDocumentTotals(items3, 'excluded', 7, 3);

  const doc3: DocumentModel = {
    id: 'doc-receipt-1',
    type: 'receipt',
    documentNumber: 'RC-202608-001',
    referenceNumber: 'IV-202608-000',
    issueDate: '2026-08-22',
    dueDate: '2026-08-22',
    paymentTerms: 'ชำระเงินเรียบร้อยแล้ว (โอนผ่าน PromptPay)',
    company: initialCompanyInfo,
    customer: initialCustomers[1],
    items: items3,
    notes: 'ได้รับเงินและภาษีหัก ณ ที่จ่ายเรียบร้อยแล้ว ขอขอบพระคุณที่ใช้บริการ',
    termsAndConditions: 'เอกสารนี้จะสมบูรณ์เมื่อมีลายมือชื่อของผู้รับเงิน หรือได้รับการชำระเงินทางบัญชีธนาคารเรียบร้อยแล้ว',
    vatType: 'excluded',
    vatRate: 7,
    withholdingTaxRate: 3,
    ...totals3,
    status: 'paid',
    templateStyle: 'corporate',
    language: 'th',
    showPromptPayQR: true,
    promptPayId: initialCompanyInfo.promptPayId,
    selectedBankAccountId: 'bank-1',
    showSignature: true,
    showStamp: true,
    preparedByName: 'นายสมชาย รุ่งเรืองทรัพย์',
    receivedByName: 'นายสมชาย รุ่งเรืองทรัพย์',
    createdAt: '2026-08-22T14:15:00.000Z',
    updatedAt: '2026-08-22T14:15:00.000Z',
  };

  // Sample Billing Note
  const items4 = [
    {
      id: 'item-bn-1',
      code: 'LIC-ERP-04',
      name: 'ใบส่งมอบและวางบิล: สิทธิ์การใช้งานระบบคลังสินค้า ERP SaaS (งวดที่ 1)',
      description: 'ส่งมอบระบบ User Credentials และคู่มือการใช้งาน 1 ชุด',
      quantity: 2,
      unit: 'ชุด',
      unitPrice: 12500,
      discountType: 'percent' as const,
      discountValue: 5,
      isTaxable: true,
      total: 23750,
    },
  ];
  const totals4 = calculateDocumentTotals(items4, 'excluded', 7, 3);

  const doc4: DocumentModel = {
    id: 'doc-billing-1',
    type: 'billing',
    documentNumber: 'BN-202608-001',
    referenceNumber: 'DO-202608-112',
    issueDate: '2026-08-25',
    dueDate: '2026-09-25',
    paymentTerms: 'กำหนดชำระเงินภายใน 30 วัน',
    company: initialCompanyInfo,
    customer: initialCustomers[2],
    items: items4,
    notes: 'ได้รับสินค้า/บริการตามรายการข้างต้นในสภาพเรียบร้อยและครบถ้วนถูกต้องแล้ว',
    termsAndConditions: 'กรุณาตรวจสอบรายการสินค้าและเอกสาร หากมีข้อทักท้วงกรุณาแจ้งภายใน 7 วัน',
    vatType: 'excluded',
    vatRate: 7,
    withholdingTaxRate: 3,
    ...totals4,
    status: 'pending',
    templateStyle: 'classic',
    language: 'th',
    showPromptPayQR: true,
    promptPayId: initialCompanyInfo.promptPayId,
    selectedBankAccountId: 'bank-1',
    showSignature: true,
    showStamp: false,
    preparedByName: 'นายสมชาย รุ่งเรืองทรัพย์',
    createdAt: '2026-08-25T11:00:00.000Z',
    updatedAt: '2026-08-25T11:00:00.000Z',
  };

  return [doc1, doc2, doc3, doc4];
}
